/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lichao_jni_JNI */

#ifndef _Included_com_dpower_pub_dp2700_tools_JniBase64Code
#define _Included_com_dpower_pub_dp2700_tools_JniBase64Code
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dpower_pub_dp2700_tools_JniBase64Code
 * Method:    enBase
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dpower_pub_dp2700_tools_JniBase64Code_enBase
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_dpower_pub_dp2700_tools_JniBase64Code
 * Method:    deBase
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dpower_pub_dp2700_tools_JniBase64Code_deBase
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
